language: java
jdk:
  - oraclejdk8

services:
  - docker
sudo: required

before_install:
  -  docker build -t dos - < Dockerfile
  -  docker run -t -i dos sh -c 'java -version'

before_script:
  -  ls target
  -  docker run -t -i dos sh -c 'ifconfig'
  -  ls /home/travis/build/dzitkowskik/mini-dos -a


script: mvn integration-test
